/**
 * /trust — HAPPY Trust Center (public).
 * App-owner maintained page describing HAPPY's practices and platform
 * controls. Not an independent certification.
 */
import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Shield, Lock, Eye, Sparkles, Accessibility, Users, FileText,
  Cookie, ScrollText, Building2, HandHelping, Mail,
} from "lucide-react";

export const Route = createFileRoute("/trust")({
  head: () => ({
    meta: [
      { title: "Trust Center — HAPPY" },
      { name: "description", content: "How HAPPY protects privacy, security, and human oversight across the platform." },
      { property: "og:title", content: "Trust Center — HAPPY" },
      { property: "og:description", content: "Privacy, security, responsible AI, and human oversight at HAPPY." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: TrustCenter,
});

type Section = { id: string; title: string; icon: typeof Shield; body: string };

const SECTIONS: Section[] = [
  { id: "privacy", title: "Privacy", icon: Lock, body:
    "We collect only what HAPPY needs to serve you: account details you provide, the content you create, and diagnostic data required to keep the platform reliable. We do not sell personal data. You can request export or deletion of your data at any time by contacting us." },
  { id: "responsible-ai", title: "Responsible AI", icon: Sparkles, body:
    "HAPPY is designed to augment human judgment, not replace it. Outputs may be imperfect and should be reviewed before consequential decisions. We do not use your private conversations to train third-party models without explicit consent." },
  { id: "ai-transparency", title: "AI Transparency", icon: Eye, body:
    "HAPPY is an AI. Every response — spoken or written — is generated by underlying language and speech models. HAPPY reveals its AI nature on request and never claims to be human." },
  { id: "security", title: "Security", icon: Shield, body:
    "The platform runs on managed cloud infrastructure with encryption in transit (TLS) and at rest, role-based access control, row-level security on user data, and audit logging on privileged operations." },
  { id: "accessibility", title: "Accessibility", icon: Accessibility, body:
    "HAPPY honors prefers-reduced-motion, offers captions, large text, high-contrast mode, keyboard navigation, screen-reader labels on controls, and push-to-talk voice input as a keyboard alternative." },
  { id: "human-oversight", title: "Human Oversight", icon: Users, body:
    "You remain in control. HAPPY does not take autonomous action outside features you invoke. Interruption, cancellation, and revocation of any voice or agent session are always one control away." },
  { id: "compliance", title: "Enterprise Compliance", icon: Building2, body:
    "HAPPY is built for enterprise deployment: multi-tenant isolation, admin controls, exportable audit logs, and configurable data-retention policies. Specific certifications and contractual DPAs are handled per-customer — contact us for the current posture and scope." },
  { id: "data-protection", title: "Data Protection", icon: FileText, body:
    "We minimize personal data, restrict access on a need-to-know basis, and separate operational logs from user content. Backups are encrypted and access is audited. You can request retention limits appropriate to your workspace." },
  { id: "cookies", title: "Cookie Policy", icon: Cookie, body:
    "HAPPY uses cookies and local storage only for essential authentication and to remember your preferences (theme, captions, voice speed). We do not set third-party advertising cookies." },
  { id: "terms", title: "Terms", icon: ScrollText, body:
    "By using HAPPY you agree to use the service lawfully, refrain from generating harmful or illegal content, and take responsibility for how you apply HAPPY's output. The service is provided as-is under the current terms — contact us for a signed commercial agreement." },
  { id: "contact", title: "Contact Security Team", icon: Mail, body:
    "Report security concerns, vulnerabilities, or privacy questions to security@happyx.ai. We acknowledge receipt within one business day and coordinate responsible disclosure." },
  { id: "limitations", title: "Model Limitations", icon: HandHelping, body:
    "HAPPY may occasionally produce inaccurate, incomplete, or outdated information. Do not rely on HAPPY as the sole source for medical, legal, financial, or safety-critical decisions." },
];

function TrustCenter() {
  return (
    <div className="min-h-screen bg-obsidian text-paper">
      <header className="border-b border-gold/10 bg-obsidian/80 backdrop-blur sticky top-0 z-30">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <Link to="/" className="text-sm font-semibold tracking-tight text-paper hover:text-gold">← HAPPY</Link>
          <span className="text-[10px] uppercase tracking-[0.28em] text-gold/70">Trust Center</span>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-6 py-16">
        <section className="text-center">
          <p className="text-[11px] uppercase tracking-[0.3em] text-gold">Trust · Privacy · Security</p>
          <h1 className="mt-4 font-display text-4xl md:text-5xl font-medium text-paper">Trust Center</h1>
          <p className="mx-auto mt-4 max-w-2xl text-sm md:text-base text-soft-gray">
            This page is maintained by HAPPY PERSON PRIVATE LIMITED to answer common security, privacy, and responsible-AI questions about HAPPY. It is not an independent certification.
          </p>
        </section>

        <nav aria-label="Trust center sections" className="mt-12 grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4">
          {SECTIONS.map((s) => (
            <a key={s.id} href={`#${s.id}`}
              className="rounded-lg border border-white/10 bg-white/[0.02] px-3 py-2 text-xs text-soft-gray hover:border-gold/40 hover:text-paper focus-visible:outline focus-visible:outline-2 focus-visible:outline-gold">
              {s.title}
            </a>
          ))}
        </nav>

        <div className="mt-14 grid gap-6 md:grid-cols-2">
          {SECTIONS.map((s) => (
            <section key={s.id} id={s.id} className="scroll-mt-24 rounded-2xl border border-white/10 bg-white/[0.02] p-6">
              <div className="flex items-center gap-3">
                <span className="grid h-9 w-9 place-items-center rounded-full bg-gold/10 text-gold ring-1 ring-gold/25">
                  <s.icon className="h-4 w-4" />
                </span>
                <h2 className="text-lg font-medium text-paper">{s.title}</h2>
              </div>
              <p className="mt-3 text-sm leading-relaxed text-soft-gray">{s.body}</p>
            </section>
          ))}
        </div>

        <section className="mt-16 rounded-2xl border border-gold/20 bg-gold/5 p-8 text-center">
          <h2 className="font-display text-xl font-medium text-paper">Shared Responsibility</h2>
          <p className="mx-auto mt-3 max-w-2xl text-sm text-soft-gray">
            HAPPY provides platform-level controls: encryption, access management, audit logging, and reliability engineering.
            Workspace owners are responsible for their user provisioning, data classification, retention rules, and how their teams apply HAPPY's output.
            Users are responsible for lawful, honest, and safe use.
          </p>
        </section>

        <footer className="mt-16 border-t border-white/5 pt-8 text-center text-[11px] uppercase tracking-[0.24em] text-soft-gray">
          <p>HAPPY PERSON PRIVATE LIMITED · Enterprise Edition v1.0</p>
          <p className="mt-2">Last reviewed {new Date().toLocaleDateString(undefined, { year: "numeric", month: "long" })}</p>
          <div className="mt-4 flex justify-center gap-6">
            <Link to="/" className="hover:text-paper">Home</Link>
            <Link to="/status" className="hover:text-paper">Status</Link>
          </div>
        </footer>
      </main>
    </div>
  );
}
