/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedFounderRouteImport } from './routes/_authenticated/founder'
import { Route as AuthenticatedEnterpriseRouteImport } from './routes/_authenticated/enterprise'
import { Route as AuthenticatedEducationRouteImport } from './routes/_authenticated/education'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedFounderIndexRouteImport } from './routes/_authenticated/founder.index'
import { Route as AuthenticatedFounderUsersRouteImport } from './routes/_authenticated/founder.users'
import { Route as AuthenticatedFounderSystemRouteImport } from './routes/_authenticated/founder.system'
import { Route as AuthenticatedFounderSecurityRouteImport } from './routes/_authenticated/founder.security'
import { Route as AuthenticatedFounderOpsRouteImport } from './routes/_authenticated/founder.ops'
import { Route as AuthenticatedFounderCompaniesRouteImport } from './routes/_authenticated/founder.companies'
import { Route as AuthenticatedFounderAnalyticsRouteImport } from './routes/_authenticated/founder.analytics'
import { Route as AuthenticatedFounderAiRouteImport } from './routes/_authenticated/founder.ai'
import { Route as ApiPublicV1StatusRouteImport } from './routes/api/public/v1/status'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'

const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFounderRoute = AuthenticatedFounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnterpriseRoute = AuthenticatedEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEducationRoute = AuthenticatedEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFounderIndexRoute =
  AuthenticatedFounderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedFounderUsersRoute =
  AuthenticatedFounderUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedFounderSystemRoute =
  AuthenticatedFounderSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedFounderSecurityRoute =
  AuthenticatedFounderSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedFounderOpsRoute = AuthenticatedFounderOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedFounderRoute,
} as any)
const AuthenticatedFounderCompaniesRoute =
  AuthenticatedFounderCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedFounderAnalyticsRoute =
  AuthenticatedFounderAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedFounderRoute,
  } as any)
const AuthenticatedFounderAiRoute = AuthenticatedFounderAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedFounderRoute,
} as any)
const ApiPublicV1StatusRoute = ApiPublicV1StatusRouteImport.update({
  id: '/api/public/v1/status',
  path: '/api/public/v1/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/design': typeof DesignRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/education': typeof AuthenticatedEducationRoute
  '/enterprise': typeof AuthenticatedEnterpriseRoute
  '/founder': typeof AuthenticatedFounderRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/founder/ai': typeof AuthenticatedFounderAiRoute
  '/founder/analytics': typeof AuthenticatedFounderAnalyticsRoute
  '/founder/companies': typeof AuthenticatedFounderCompaniesRoute
  '/founder/ops': typeof AuthenticatedFounderOpsRoute
  '/founder/security': typeof AuthenticatedFounderSecurityRoute
  '/founder/system': typeof AuthenticatedFounderSystemRoute
  '/founder/users': typeof AuthenticatedFounderUsersRoute
  '/founder/': typeof AuthenticatedFounderIndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/design': typeof DesignRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/education': typeof AuthenticatedEducationRoute
  '/enterprise': typeof AuthenticatedEnterpriseRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/founder/ai': typeof AuthenticatedFounderAiRoute
  '/founder/analytics': typeof AuthenticatedFounderAnalyticsRoute
  '/founder/companies': typeof AuthenticatedFounderCompaniesRoute
  '/founder/ops': typeof AuthenticatedFounderOpsRoute
  '/founder/security': typeof AuthenticatedFounderSecurityRoute
  '/founder/system': typeof AuthenticatedFounderSystemRoute
  '/founder/users': typeof AuthenticatedFounderUsersRoute
  '/founder': typeof AuthenticatedFounderIndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/design': typeof DesignRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/education': typeof AuthenticatedEducationRoute
  '/_authenticated/enterprise': typeof AuthenticatedEnterpriseRoute
  '/_authenticated/founder': typeof AuthenticatedFounderRouteWithChildren
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/founder/ai': typeof AuthenticatedFounderAiRoute
  '/_authenticated/founder/analytics': typeof AuthenticatedFounderAnalyticsRoute
  '/_authenticated/founder/companies': typeof AuthenticatedFounderCompaniesRoute
  '/_authenticated/founder/ops': typeof AuthenticatedFounderOpsRoute
  '/_authenticated/founder/security': typeof AuthenticatedFounderSecurityRoute
  '/_authenticated/founder/system': typeof AuthenticatedFounderSystemRoute
  '/_authenticated/founder/users': typeof AuthenticatedFounderUsersRoute
  '/_authenticated/founder/': typeof AuthenticatedFounderIndexRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/status': typeof ApiPublicV1StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/design'
    | '/assistant'
    | '/business'
    | '/community'
    | '/dashboard'
    | '/education'
    | '/enterprise'
    | '/founder'
    | '/knowledge'
    | '/marketplace'
    | '/settings'
    | '/studio'
    | '/founder/ai'
    | '/founder/analytics'
    | '/founder/companies'
    | '/founder/ops'
    | '/founder/security'
    | '/founder/system'
    | '/founder/users'
    | '/founder/'
    | '/api/public/v1/health'
    | '/api/public/v1/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/design'
    | '/assistant'
    | '/business'
    | '/community'
    | '/dashboard'
    | '/education'
    | '/enterprise'
    | '/knowledge'
    | '/marketplace'
    | '/settings'
    | '/studio'
    | '/founder/ai'
    | '/founder/analytics'
    | '/founder/companies'
    | '/founder/ops'
    | '/founder/security'
    | '/founder/system'
    | '/founder/users'
    | '/founder'
    | '/api/public/v1/health'
    | '/api/public/v1/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/design'
    | '/_authenticated/assistant'
    | '/_authenticated/business'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/education'
    | '/_authenticated/enterprise'
    | '/_authenticated/founder'
    | '/_authenticated/knowledge'
    | '/_authenticated/marketplace'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/founder/ai'
    | '/_authenticated/founder/analytics'
    | '/_authenticated/founder/companies'
    | '/_authenticated/founder/ops'
    | '/_authenticated/founder/security'
    | '/_authenticated/founder/system'
    | '/_authenticated/founder/users'
    | '/_authenticated/founder/'
    | '/api/public/v1/health'
    | '/api/public/v1/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DesignRoute: typeof DesignRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1StatusRoute: typeof ApiPublicV1StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founder': {
      id: '/_authenticated/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof AuthenticatedFounderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enterprise': {
      id: '/_authenticated/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof AuthenticatedEnterpriseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education': {
      id: '/_authenticated/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof AuthenticatedEducationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/founder/': {
      id: '/_authenticated/founder/'
      path: '/'
      fullPath: '/founder/'
      preLoaderRoute: typeof AuthenticatedFounderIndexRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/users': {
      id: '/_authenticated/founder/users'
      path: '/users'
      fullPath: '/founder/users'
      preLoaderRoute: typeof AuthenticatedFounderUsersRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/system': {
      id: '/_authenticated/founder/system'
      path: '/system'
      fullPath: '/founder/system'
      preLoaderRoute: typeof AuthenticatedFounderSystemRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/security': {
      id: '/_authenticated/founder/security'
      path: '/security'
      fullPath: '/founder/security'
      preLoaderRoute: typeof AuthenticatedFounderSecurityRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/ops': {
      id: '/_authenticated/founder/ops'
      path: '/ops'
      fullPath: '/founder/ops'
      preLoaderRoute: typeof AuthenticatedFounderOpsRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/companies': {
      id: '/_authenticated/founder/companies'
      path: '/companies'
      fullPath: '/founder/companies'
      preLoaderRoute: typeof AuthenticatedFounderCompaniesRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/analytics': {
      id: '/_authenticated/founder/analytics'
      path: '/analytics'
      fullPath: '/founder/analytics'
      preLoaderRoute: typeof AuthenticatedFounderAnalyticsRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/_authenticated/founder/ai': {
      id: '/_authenticated/founder/ai'
      path: '/ai'
      fullPath: '/founder/ai'
      preLoaderRoute: typeof AuthenticatedFounderAiRouteImport
      parentRoute: typeof AuthenticatedFounderRoute
    }
    '/api/public/v1/status': {
      id: '/api/public/v1/status'
      path: '/api/public/v1/status'
      fullPath: '/api/public/v1/status'
      preLoaderRoute: typeof ApiPublicV1StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedFounderRouteChildren {
  AuthenticatedFounderAiRoute: typeof AuthenticatedFounderAiRoute
  AuthenticatedFounderAnalyticsRoute: typeof AuthenticatedFounderAnalyticsRoute
  AuthenticatedFounderCompaniesRoute: typeof AuthenticatedFounderCompaniesRoute
  AuthenticatedFounderOpsRoute: typeof AuthenticatedFounderOpsRoute
  AuthenticatedFounderSecurityRoute: typeof AuthenticatedFounderSecurityRoute
  AuthenticatedFounderSystemRoute: typeof AuthenticatedFounderSystemRoute
  AuthenticatedFounderUsersRoute: typeof AuthenticatedFounderUsersRoute
  AuthenticatedFounderIndexRoute: typeof AuthenticatedFounderIndexRoute
}

const AuthenticatedFounderRouteChildren: AuthenticatedFounderRouteChildren = {
  AuthenticatedFounderAiRoute: AuthenticatedFounderAiRoute,
  AuthenticatedFounderAnalyticsRoute: AuthenticatedFounderAnalyticsRoute,
  AuthenticatedFounderCompaniesRoute: AuthenticatedFounderCompaniesRoute,
  AuthenticatedFounderOpsRoute: AuthenticatedFounderOpsRoute,
  AuthenticatedFounderSecurityRoute: AuthenticatedFounderSecurityRoute,
  AuthenticatedFounderSystemRoute: AuthenticatedFounderSystemRoute,
  AuthenticatedFounderUsersRoute: AuthenticatedFounderUsersRoute,
  AuthenticatedFounderIndexRoute: AuthenticatedFounderIndexRoute,
}

const AuthenticatedFounderRouteWithChildren =
  AuthenticatedFounderRoute._addFileChildren(AuthenticatedFounderRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEducationRoute: typeof AuthenticatedEducationRoute
  AuthenticatedEnterpriseRoute: typeof AuthenticatedEnterpriseRoute
  AuthenticatedFounderRoute: typeof AuthenticatedFounderRouteWithChildren
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEducationRoute: AuthenticatedEducationRoute,
  AuthenticatedEnterpriseRoute: AuthenticatedEnterpriseRoute,
  AuthenticatedFounderRoute: AuthenticatedFounderRouteWithChildren,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DesignRoute: DesignRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1StatusRoute: ApiPublicV1StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
